### ISSUE TITLE
Resolution Problems

### ISSUE THREAD

**Issue by nachomim** [Sewer56/Heroes-Graphics-Essentials#10]
Hi, first of all thanks for your help.
I've tried every setting possible and I always got the same issue.

![error](https://user-images.githubusercontent.com/9118749/59481708-57dba700-8e33-11e9-87d3-e684d647b031.png)

Any idea?

These are my settings.

> {
  "Width": 3840,
  "Height": 2160,
  "Fullscreen": false,
  "Borderless": true,
  "Resizable": false,
  "Disable2PFrameskip": true,
  "AspectRatioLimit": 1.33333337,
  "StupidlyFastLoadTimes": true,
  "EnableAspectHack": true,
  "AlternateAspectScaling": false,
  "D3D9Settings": {
    "Enable": true,
    "EnableMSAA": true,
    "EnableAF": true,
    "MSAALevel": 4,
    "AFLevel": 16,
    "VSync": true,
    "HardwareVertexProcessing": true
  },
  "DefaultSettings": {
    "Language": 1,
    "SFXVolume": 100,
    "BGMVolume": 100,
    "ThreeDimensionalSound": true,
    "SFXOn": true,
    "BGMOn": true,
    "SoftShadows": true,
    "MouseControl": -1,
    "CharmyShutup": false
  }
}

Thank you.

**Comment by Sewer56** [comment]
No idea here.

Pressing `Alt+F4` and hitting cancel at the prompt to reset `DirectX` and the `RenderWare Maestro` (Menu Graphics) being rendered would probably fix it - though that said nothing comes to mind as for why the Maestro would render at such a weird resolution.

It's possible that something is changing the window size of the game right before the menus are to be rendered: The mod does actually change the window size for initialising stage load screens to fix crashes when being ran at very wide/tall aspect ratios but that happens so quickly the window size change is never actually committed.

**Comment by nachomim** [comment]
Thank you for your answer.
I was able to fix the problem replacing the files from the 
> Sonic Heroes Settings plugin

May be the problem was in the file
> Tsonic_win.exe

Not sure...
The files I added are

> Dinput8.dll
> Dinput.dll
> XInput1_3.dll
> XInputPlus.ini

Greeting!
