### ISSUE TITLE
Hang Castle Moon stretches in non-4:3 aspect ratios

### ISSUE THREAD

**Issue by cheatfreak47** [Sewer56/Heroes-Graphics-Essentials#2]
When running Sonic Heroes in a non 4:3 resolution, the moon in Hang Castle (**and potentially other 2D sky graphical elements**) all render stretched. 

![tsonic_win_2018-12-12_16-08-07](https://user-images.githubusercontent.com/7818664/49969135-cd52d300-fef5-11e8-87b6-a3570f12bfb0.png)

(This seems to be a typical problem with renderware games, since the same thing happened to GTA3, VC, and SA.)

**Comment by Muzzarino** [comment]
That's not stretched, the moon is like that especially on normal 4:3 due to the fact that it's part of the geometry.

**Comment by cheatfreak47** [comment]
Is that so? I could've sworn that it wasn't so wide when running in 4:3, I'll double check this later today and reopen it if I wasn't wrong.
